import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { getAdminOrder, updateOrderStatus } from "../services/api.js";
import "./pages.css";
import "./Orders.css";
import "./Admin.css";

const transitions = { pending: ["confirmed", "cancelled"], confirmed: ["shipped", "cancelled"], shipped: ["delivered"], delivered: [], cancelled: [] };
function AdminOrderDetails() { const { id } = useParams(); const navigate = useNavigate(); const [order, setOrder] = useState(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); useEffect(() => { getAdminOrder(id).then(setOrder).catch((err) => setError(err.message)); }, [id]); const update = async (status) => { setSaving(true); try { setOrder(await updateOrderStatus(id, status)); } catch (err) { setError(err.message); } finally { setSaving(false); } }; if (error) return <div className="page-state error">{error}</div>; if (!order) return <div className="page-state">Loading order...</div>; return <main className="page-shell"><div className="admin-heading"><div className="page-heading"><h1>Order #{order.id.slice(-8)}</h1><p>Customer: {order.user_id}</p></div><button className="secondary-button" onClick={() => navigate("/admin/orders")}>Back to orders</button></div><section className="order-detail-card"><div className="order-detail-card__header"><b className={`status status--${order.status}`}>{order.status}</b><span>{order.items.length} item(s)</span></div>{order.items.map((item) => <div className="order-item" key={item.product_id}><div><strong>Product {item.product_id}</strong><span>Quantity: {item.quantity}</span><span>₹{item.price.toFixed(2)} each</span></div><b>₹{(item.price * item.quantity).toFixed(2)}</b></div>)}<div className="order-total"><span>Total</span><strong>₹{order.total_amount.toFixed(2)}</strong></div><div className="inline-actions">{transitions[order.status].map((status) => <button className={status === "cancelled" ? "danger-button" : "primary-button"} disabled={saving} key={status} onClick={() => update(status)}>Mark {status}</button>)}</div></section></main>; }
export default AdminOrderDetails;
